// Single source of truth for which real photo albums exist for Our Programs.
// Used by both the admin "Our Programs" photo panel and the public Gallery page,
// so the two never drift out of sync. Each folder maps to website/programs/{status}/{folder}/
// in Cloudflare R2 — only albums with real, matched photographs appear here.
export type AlbumCategory = "agriculture" | "nrm" | "health" | "child";

export type ProgramAlbum = {
  folder: string;
  status: "completed" | "ongoing";
  label: string;
  location: string;
  year: string;
  desc: string;
  category: AlbumCategory;
  covers: string[]; // project name(s) this album's photos illustrate
};

export const programAlbums: ProgramAlbum[] = [
  {
    folder: "azim-premji-climate-resilient",
    status: "ongoing",
    label: "Climate-Resilient Farming (Azim Premji Foundation)",
    location: "24 Villages, Prakasam District, Andhra Pradesh",
    year: "2024–2025",
    desc: "Improving livelihoods of 1,904 small & marginal farmers and 1,435 landless agricultural labourers through climate-resilient integrated farming systems and resource conservation.",
    category: "agriculture",
    covers: ["Integrated Climate-Resilient Farming Systems for Sustainable Livelihoods and Water Conservation"],
  },
  {
    folder: "varaha-carbon-sequestration",
    status: "ongoing",
    label: "Carbon Sequestration Project (VARAHA)",
    location: "500 Acres, Andhra Pradesh",
    year: "2025–2026",
    desc: "Reducing carbon through horticulture and timber species plantation, promoting verified carbon credits — one of EFFORT's rare carbon-credit-exclusive projects.",
    category: "nrm",
    covers: ["Carbon Sequestration Project"],
  },
  {
    folder: "reliance-foundation",
    status: "ongoing",
    label: "Reliance Foundation — Prakasam Resilience",
    location: "Prakasam District, Andhra Pradesh",
    year: "2024–2025",
    desc: "Building resilient communities with the strength to overcome social, educational, health, environmental and economic hardships.",
    category: "agriculture",
    covers: ["Improving Self-Reliance and Resilience of Rural Communities in Prakasam District"],
  },
  {
    folder: "fpo-promotion-nabard",
    status: "ongoing",
    label: "Farmers Producer Organisations (NABARD)",
    location: "150 villages, Andhra Pradesh",
    year: "2023–2025",
    desc: "Sensitising and organising small & marginal farmers to address farmer-related issues.",
    category: "agriculture",
    covers: ["Promotion & Strengthening of Farmers Producer Organisations"],
  },
  {
    folder: "biodiversity-water-gpi",
    status: "ongoing",
    label: "Bio-diversity Park & Water Harvesting (Godfrey Phillips)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Creating biodiversity parks to boost ecosystems and promote soil, water and native flora conservation.",
    category: "nrm",
    covers: ["Promotion of Bio-diversity Conservation Park and Water Harvesting Structures"],
  },
  {
    folder: "dka-nrm-kurnool",
    status: "ongoing",
    label: "Climate-Resilient Farming, Kurnool (DKA Austria)",
    location: "Aluru Mandal, Kurnool District",
    year: "2023–2025",
    desc: "Climate-resilient agro-ecological approaches across 5 villages, covering 250 small & marginal farmers.",
    category: "nrm",
    covers: ["Promotion of Climate Resilient Farming through Effective Natural Resource Management"],
  },
  {
    folder: "jsw-water-governance",
    status: "ongoing",
    label: "Water Governance (JSW Foundation)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Developing 'Water Plus Villages' ensuring water security, ecological restoration and biodiversity protection.",
    category: "nrm",
    covers: ["Water Governance and Management Project"],
  },
  {
    folder: "chilli-value-chain-idh",
    status: "ongoing",
    label: "Chilli Value Chain (IDH Netherlands)",
    location: "South India",
    year: "2023–2025",
    desc: "Increasing farming incomes through better price discovery and stabilised yields of red chillies.",
    category: "agriculture",
    covers: ["Integrated Agri Extension Project in Chilli Value Chain"],
  },
  {
    folder: "prakasam-nri-schools",
    status: "ongoing",
    label: "School Amenities (Prakasam Global NRI Forum)",
    location: "Prakasam District, Andhra Pradesh",
    year: "2023–2025",
    desc: "Providing amenities and infrastructure in government schools to ensure 100% school education.",
    category: "child",
    covers: ["Strengthening Amenities in Government Schools"],
  },
  {
    folder: "sustainable-wellbeing-women",
    status: "ongoing",
    label: "Women's Well-Being (EKAMUSA & Orange Elephant)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Women's empowerment and improved livelihoods through livelihood interventions.",
    category: "child",
    covers: ["Sustainable Well-Being of Women"],
  },
  {
    folder: "nabard-sri-paddy",
    status: "completed",
    label: "SRI Paddy Pilot Project (NABARD)",
    location: "16 Villages, Andhra Pradesh",
    year: "1999–2023",
    desc: "Educating 400 farmers across 16 villages on System of Rice Intensification (SRI) paddy cultivation, covering 400 acres of demonstration plots.",
    category: "agriculture",
    covers: ["Pilot Project on SRI Paddy"],
  },
  {
    folder: "nabard-tribal-dev-fund",
    status: "completed",
    label: "Tribal Development Fund — Wadi Approach (NABARD)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Promoting sustainable livelihoods for 1,000 tribal families through horticulture crops via the Wadi approach.",
    category: "agriculture",
    covers: ["Tribal Development Fund Project"],
  },
  {
    folder: "nabard-watershed-dev-fund",
    status: "completed",
    label: "Watershed Development Fund (NABARD)",
    location: "3 Districts, Andhra Pradesh",
    year: "1999–2023",
    desc: "90 watershed projects addressing farmer distress across 3 districts of Andhra Pradesh, with EFFORT acting as Regional Support Organisation (RSO).",
    category: "agriculture",
    covers: ["Watershed Development Fund Projects Addressing Farmer Distress"],
  },
  {
    folder: "nabard-umbrella-nrm",
    status: "completed",
    label: "Umbrella Programme for NRM (NABARD)",
    location: "13 Villages, Andhra Pradesh",
    year: "1999–2023",
    desc: "Sustainable livelihoods for rural poor dependent on natural resources across 13 villages, covering 500 families.",
    category: "nrm",
    covers: ["Umbrella Programme for Natural Resource Management"],
  },
  {
    folder: "nabard-farmer-clubs",
    status: "completed",
    label: "Farmer Clubs (NABARD)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "NABARD Farmer Club formation, building grassroots farmer collectives for knowledge-sharing and collective bargaining.",
    category: "agriculture",
    covers: ["NABARD Farmer Clubs"],
  },
  {
    folder: "spices-board-ipm-chilli",
    status: "completed",
    label: "IPM in Chilli (Spices Board)",
    location: "Prakasam & Guntur Districts, Andhra Pradesh",
    year: "1999–2023",
    desc: "Integrated Pest Management, Vermi Compost promotion, post-harvest technologies and organic farming capacity building for chilli-growing farmers.",
    category: "agriculture",
    covers: ["Integrated Pest Management in Chilli / Vermi Compost / Organic Farming"],
  },
  {
    folder: "apchip",
    status: "completed",
    label: "AP Community Health Intervention (APCHIP)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Reducing incidence of TB, HIV/AIDS, Malaria, Filaria and Leprosy across 12 villages.",
    category: "health",
    covers: ["Andhra Pradesh Community Health Intervention Project"],
  },
  {
    folder: "apsacs-hiv-aids",
    status: "completed",
    label: "Swagati HIV/AIDS Interventions (APSACS)",
    location: "Markapur Revenue Division, Andhra Pradesh",
    year: "1999–2023",
    desc: "HIV/AIDS interventions across 8 mandals of Markapur revenue division.",
    category: "health",
    covers: ["Swagati HIV/AIDS Interventions Project"],
  },
  {
    folder: "millepede-watershed",
    status: "completed",
    label: "Watershed Livelihoods (Millepede Foundation)",
    location: "Jaganadhapuram",
    year: "1999–2023",
    desc: "Conservation of natural resources for promotion of livelihoods through a watershed approach.",
    category: "nrm",
    covers: ["Conservation of Natural Resources for Promotion of Livelihoods through Watershed Approach"],
  },
  {
    folder: "dsr-punjab-haryana-mp-up",
    status: "completed",
    label: "Direct Seeded Rice — Punjab, Haryana, MP & UP",
    location: "Punjab, Haryana, Madhya Pradesh, Uttar Pradesh",
    year: "1999–2023",
    desc: "Enhancing skills & knowledge of 1,00,000 paddy-cultivating farmers on DSR practices.",
    category: "agriculture",
    covers: ["Spreading Happiness through Sustainable Rice Farming (DSR)"],
  },
  {
    folder: "mustard-bee-pollination",
    status: "completed",
    label: "Mustard & Bee Pollination",
    location: "4 states of India",
    year: "1999–2023",
    desc: "Improving mustard crop productivity for farmers through beekeeping and bee pollination.",
    category: "agriculture",
    covers: [
      "Improving Crop Productivity of Mustard through Bee Pollination (Corteva)",
      "Honeybee Project in Mustard Cultivation (PHI Seeds)",
    ],
  },
  {
    folder: "organic-ginger-giz",
    status: "completed",
    label: "Organic Ginger Cultivation (GIZ)",
    location: "Vizag District, Andhra Pradesh",
    year: "1999–2023",
    desc: "Increasing ginger productivity by 20% and net income of 750 farmers by 25% across 28 villages.",
    category: "agriculture",
    covers: ["Promotion and Strengthening of Sustainable Integrated Ginger Cultivation"],
  },
  {
    folder: "ipm-chilli-iffco",
    status: "completed",
    label: "IPM in Chilli (Iffco Kisan)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Sensitising 500 chilli farmers to produce residue-free chilli and develop marketing linkages.",
    category: "agriculture",
    covers: ["Integrated Pest Management (IPM) in Chilli Cultivation"],
  },
  {
    folder: "rythu-bazaar-market",
    status: "completed",
    label: "Farmer Market Linkages (Syngenta)",
    location: "Khammam District, Telangana & Andhra Pradesh",
    year: "1999–2023",
    desc: "Marketing infrastructure enabling small & marginal farmers to sell produce directly to customers.",
    category: "agriculture",
    covers: ["Promotion of Wayside Market", "Promotion of Rythu Bazaar at Khammam District"],
  },
  {
    folder: "ro-water-plants",
    status: "completed",
    label: "RO Water Plants & Sanitation (Universal Leaf)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Supporting farming communities with safe drinking water through RO plants, school sanitary block promotion and tank renovation.",
    category: "health",
    covers: ["Community Development Interventions"],
  },
];

export const ALBUM_CATEGORY_LABELS: Record<AlbumCategory, string> = {
  agriculture: "Agriculture",
  nrm: "Environment & Water",
  health: "Health & WASH",
  child: "Child & Women",
};
