// Single source of truth for which real photo albums exist for Our Programs.
// Used by both the admin "Our Programs" photo panel and the public Gallery page,
// so the two never drift out of sync. Each folder maps to website/programs/{status}/{folder}/
// in Cloudflare R2 — only albums with real, matched photographs appear here.
export type ProgramAlbum = {
  folder: string;
  status: "completed" | "ongoing";
  label: string;
  location: string;
  year: string;
  desc: string;
  covers: string[]; // project name(s) this album's photos illustrate
};

export const programAlbums: ProgramAlbum[] = [
  {
    folder: "reliance-foundation",
    status: "ongoing",
    label: "Reliance Foundation — Prakasam Resilience",
    location: "Prakasam District, Andhra Pradesh",
    year: "2024–2025",
    desc: "Building resilient communities with the strength to overcome social, educational, health, environmental and economic hardships.",
    covers: ["Improving Self-Reliance and Resilience of Rural Communities in Prakasam District"],
  },
  {
    folder: "fpo-promotion-nabard",
    status: "ongoing",
    label: "Farmers Producer Organisations (NABARD)",
    location: "150 villages, Andhra Pradesh",
    year: "2023–2025",
    desc: "Sensitising and organising small & marginal farmers to address farmer-related issues.",
    covers: ["Promotion & Strengthening of Farmers Producer Organisations"],
  },
  {
    folder: "biodiversity-water-gpi",
    status: "ongoing",
    label: "Bio-diversity Park & Water Harvesting (Godfrey Phillips)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Creating biodiversity parks to boost ecosystems and promote soil, water and native flora conservation.",
    covers: ["Promotion of Bio-diversity Conservation Park and Water Harvesting Structures"],
  },
  {
    folder: "dka-nrm-kurnool",
    status: "ongoing",
    label: "Climate-Resilient Farming, Kurnool (DKA Austria)",
    location: "Aluru Mandal, Kurnool District",
    year: "2023–2025",
    desc: "Climate-resilient agro-ecological approaches across 5 villages, covering 250 small & marginal farmers.",
    covers: ["Promotion of Climate Resilient Farming through Effective Natural Resource Management"],
  },
  {
    folder: "jsw-water-governance",
    status: "ongoing",
    label: "Water Governance (JSW Foundation)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Developing 'Water Plus Villages' ensuring water security, ecological restoration and biodiversity protection.",
    covers: ["Water Governance and Management Project"],
  },
  {
    folder: "chilli-value-chain-idh",
    status: "ongoing",
    label: "Chilli Value Chain (IDH Netherlands)",
    location: "South India",
    year: "2023–2025",
    desc: "Increasing farming incomes through better price discovery and stabilised yields of red chillies.",
    covers: ["Integrated Agri Extension Project in Chilli Value Chain"],
  },
  {
    folder: "prakasam-nri-schools",
    status: "ongoing",
    label: "School Amenities (Prakasam Global NRI Forum)",
    location: "Prakasam District, Andhra Pradesh",
    year: "2023–2025",
    desc: "Providing amenities and infrastructure in government schools to ensure 100% school education.",
    covers: ["Strengthening Amenities in Government Schools"],
  },
  {
    folder: "sustainable-wellbeing-women",
    status: "ongoing",
    label: "Women's Well-Being (EKAMUSA & Orange Elephant)",
    location: "Andhra Pradesh",
    year: "2023–2025",
    desc: "Women's empowerment and improved livelihoods through livelihood interventions.",
    covers: ["Sustainable Well-Being of Women"],
  },
  {
    folder: "nabard-programs",
    status: "completed",
    label: "NABARD-Funded Programs",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Field photographs spanning seven NABARD-funded initiatives — Farmers Associations, SRI Paddy, Watershed Development, NRM, Tribal Development, Banana CAT and Rural Youth Skilling.",
    covers: [
      "Promotion of Farmers Associations",
      "Pilot Project on SRI Paddy",
      "Watershed Development Fund Projects",
      "Umbrella Programme for NRM",
      "Tribal Development Fund Project",
      "Banana Farmers CAT",
      "Skill Development for Rural Youth",
    ],
  },
  {
    folder: "spices-board-ipm-chilli",
    status: "completed",
    label: "IPM in Chilli (Spices Board)",
    location: "Prakasam & Guntur Districts, Andhra Pradesh",
    year: "1999–2023",
    desc: "Integrated Pest Management, Vermi Compost promotion, post-harvest technologies and organic farming capacity building for chilli-growing farmers.",
    covers: ["Integrated Pest Management in Chilli / Vermi Compost / Organic Farming"],
  },
  {
    folder: "apchip",
    status: "completed",
    label: "AP Community Health Intervention (APCHIP)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Reducing incidence of TB, HIV/AIDS, Malaria, Filaria and Leprosy across 12 villages.",
    covers: ["Andhra Pradesh Community Health Intervention Project"],
  },
  {
    folder: "apsacs-hiv-aids",
    status: "completed",
    label: "Swagati HIV/AIDS Interventions (APSACS)",
    location: "Markapur Revenue Division, Andhra Pradesh",
    year: "1999–2023",
    desc: "HIV/AIDS interventions across 8 mandals of Markapur revenue division.",
    covers: ["Swagati HIV/AIDS Interventions Project"],
  },
  {
    folder: "millepede-watershed",
    status: "completed",
    label: "Watershed Livelihoods (Millepede Foundation)",
    location: "Jaganadhapuram",
    year: "1999–2023",
    desc: "Conservation of natural resources for promotion of livelihoods through a watershed approach.",
    covers: ["Conservation of Natural Resources for Promotion of Livelihoods through Watershed Approach"],
  },
  {
    folder: "dsr-punjab-haryana-mp-up",
    status: "completed",
    label: "Direct Seeded Rice — Punjab, Haryana, MP & UP",
    location: "Punjab, Haryana, Madhya Pradesh, Uttar Pradesh",
    year: "1999–2023",
    desc: "Enhancing skills & knowledge of 1,00,000 paddy-cultivating farmers on DSR practices.",
    covers: ["Spreading Happiness through Sustainable Rice Farming (DSR)"],
  },
  {
    folder: "mustard-bee-pollination",
    status: "completed",
    label: "Mustard & Bee Pollination",
    location: "4 states of India",
    year: "1999–2023",
    desc: "Improving mustard crop productivity for farmers through beekeeping and bee pollination.",
    covers: [
      "Improving Crop Productivity of Mustard through Bee Pollination (Corteva)",
      "Honeybee Project in Mustard Cultivation (PHI Seeds)",
    ],
  },
  {
    folder: "organic-ginger-giz",
    status: "completed",
    label: "Organic Ginger Cultivation (GIZ)",
    location: "Vizag District, Andhra Pradesh",
    year: "1999–2023",
    desc: "Increasing ginger productivity by 20% and net income of 750 farmers by 25% across 28 villages.",
    covers: ["Promotion and Strengthening of Sustainable Integrated Ginger Cultivation"],
  },
  {
    folder: "ipm-chilli-iffco",
    status: "completed",
    label: "IPM in Chilli (Iffco Kisan)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Sensitising 500 chilli farmers to produce residue-free chilli and develop marketing linkages.",
    covers: ["Integrated Pest Management (IPM) in Chilli Cultivation"],
  },
  {
    folder: "rythu-bazaar-market",
    status: "completed",
    label: "Farmer Market Linkages (Syngenta)",
    location: "Khammam District, Telangana & Andhra Pradesh",
    year: "1999–2023",
    desc: "Marketing infrastructure enabling small & marginal farmers to sell produce directly to customers.",
    covers: ["Promotion of Wayside Market", "Promotion of Rythu Bazaar at Khammam District"],
  },
  {
    folder: "ro-water-plants",
    status: "completed",
    label: "RO Water Plants & Sanitation (Universal Leaf)",
    location: "Andhra Pradesh",
    year: "1999–2023",
    desc: "Supporting farming communities with safe drinking water through RO plants, school sanitary block promotion and tank renovation.",
    covers: ["Community Development Interventions"],
  },
];
